### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by skAutomation12** [grasshopper7/junitcuke4sharedwebdriver#1]
My Design is as follows
![image](https://user-images.githubusercontent.com/43443475/60741450-0b195680-9f2f-11e9-860e-00a4eaa66e80.png)

[pkg] Locators declaration of page elements;
[pkg] Actions pg object creation and init pagefactory and methods declaration to perform actions on page elements. 
[pkg] runner has all runner classes TestNG
runner Class has @BeforeClass where I login to application before executing test steps to be performed on application to test the interface
[pkg] Steps 
==Cucumber hooks to handle test failure and screenshot @After
==Cucumber steps ==>Access to driver is important as the navigation to url and dynamic page element handling is done from within steps
[pkg] utils==> wait, read .property, ngwebdriver for angular waits. 

This all works fine when i have single thread; I tried to incorporate your design to make it parallel which i havent found any success. 

- How to access driver object from steps??
I donot want to navigate the url from page class;

**Comment by grasshopper7** [comment]
No need for constructor or beforeclass method in runner. Change the SharedDriver code as below.

```
public SharedDriver() {
         WebDriverManager.chromedriver().setup();
		WebDriver driver = DriverFactory.getDriver();
		if (driver == null) {
			driver = new ChromeDriver();
			DriverFactory.addDriver(driver);
		}
//Do your login and initial stuff here
		driver.get("http://yoursite.com/");
}
```

U can access driver anywhere as `DriverFactory.getDriver()`.
